name: ARC Test

on: workflow_dispatch

jobs:
  test:
    runs-on: medvista-runner
    strategy:
      matrix:
        job: [1,2,3,4]
    steps:
      - run: echo "Running job ${{ matrix.job }}"
      - run: sleep 60
